---
version: 2
plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-52
  bundler-audit:
    enabled: true
  brakeman:
    enabled: true
  structure:
    exclude_patterns:
      - "spec/**/*"
  duplication:
    exclude_patterns:
      - "spec/**/*"
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
exclude_patterns:
  - "config/**/*"
  - "db/**/*"
  - "bin/*"
