---
engines:
  rubocop:
    enabled: true
  bundler-audit:
    enabled: true
  fixme:
    enabled: true
    config:
      strings:
        - FIXME
        - BUG
ratings:
  paths:
  - "Gemfile.lock"
  - "app/**"
  - "lib/**"
  - "**.rb"
exclude_paths:
- "config/**/*"
- "db/**/*"
- "spec/**/*"
- "bin/*"
