AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'

Rails/FindBy:
  Enabled: false

Metrics/AbcSize:
  Max: 18

Metrics/ClassLength:
  enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 15

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented
