inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  DisplayCopNames: true
  Exclude:
    - 'config.ru'
    - 'Rakefile'
    - 'db/migrate/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'config/**/*'
    - 'bin/*'
    - 'script/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'spec/**/*'

Metrics/ModuleLength:
  Max: 150

Metrics/BlockLength:
  Exclude:
    - spec/**/*

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma

Style/NumericPredicate:
  AutoCorrect: true

Style/SymbolArray:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%w': '()'
    '%W': '()'

Style/MultilineBlockChain:
  Enabled: false

Layout/MultilineOperationIndentation:
  EnforcedStyle: indented

Layout/SpaceInLambdaLiteral:
  EnforcedStyle: require_space

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/BlockEndNewline:
  Exclude:
    - "spec/**/*"

Lint/DefEndAlignment:
  AutoCorrect: true

Lint/AmbiguousBlockAssociation:
  Exclude:
    - "spec/**/*"
