inherit_from: .rubocop_todo.yml

AllCops:
  RunRailsCops: true
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'vendor/**/*'
    - 'spec/**/*'

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Rails/FindBy:
  Enabled: false

Style/BracesAroundHashParameters:
  EnforcedStyle: context_dependent

Style/MultilineOperationIndentation:
  EnforcedStyle: indented

Metrics/MethodLength:
  Max: 15
