language: ruby
env:
  global:
    - DATABASE_URL="postgresql://postgres@localhost/travis_ci_test"
notifications:
  email: false
  slack:
    secure: J0J4BfYxVT2C0xfuHpRY6mqKfNGcef2b+4VmwAyU3BK+kZAy452p5BkPNIgmSJaj0pl4UE1dmTjFDRxyxOxF4q3KC3Ih61gYVqZ1a/3T940OokCjQowoJBiABSgXRimojTm7rlUD2Jq7zGKaJWJX/Ddinu5eOC8KcEqRh8wQ03Q=
bundler_args: "--without production staging --deployment"
before_install:
  - rvm @global do gem uninstall bundler -a -x
  - rvm @global do gem install bundler -v 1.10.6
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
script: bundle exec rake ci
cache:
  - bundler
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
      secure: "ZDY9DVPlB9Qy2tWHq1Ix1G+7VD0fV/DUvy9Y//odiFbGh1jwfS9m4MDqjZsDA7mUKLSZilpjBOjGNzGtNHtZS1IGf2Pidr9yWq1qONN11GBnza5/WjP3VFSCMH/S4a2ZupotidQBp8SAdEi89V6YHpIR9Wn+oSMt9lJKATY5hHk="
