FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# Settings API

## Account Settings [/api/v1/settings]

### Account settings details [GET]

Settings for current account

+ Response 200 (application/json)

        {
            "subdomain": "my-company-946",
            "company-name": "My lol",
            "timezone": "Europe/Madrid",
            "default-locale": "en",
            "holiday-policy-id": "5be2d5ee-5847-404e-b5c9-975bed61d9dc"
        }

