FORMAT: 1A
HOST: http://api.lvh.me:3000

# Yalty API

## Account Settings [/api/v1/settings]

### GET Account settings details [GET]

Settings for current account

+ Request (application/json)

+ Response 200 (application/json)

        {
            "subdomain": "my-company-946",
            "company_name": "My lol",
            "timezone": "Europe/Madrid",
            "default_locale": "en",
            "type": "settings"
        }

### PUT Update account settings [PUT]

Ability to update current account settings

+ Attributes
  + subdomain: my.subdomain (string) - Account subdomain
  + company_name: ABC company (string)
  + timezone: Europe/Madrid (string)
  + default_locale: en (string)
  + type: settings (string)

+ Request (application/json)

        {
            "subdomain": "my.subdomain",
            "company_name": "ABC",
            "timezone": "Europe/Madrid",
            "default_locale": "en",
            "type": "settings"
        }

+ Response 204







## Employee Attribute Definitions Collection [/api/v1/employee_attribute_definitions]

### GET List of all employee attributes definitions [GET]

Get a list of all account's Employee Attribute Definitions

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
                "id": "12345678-1234-1234-1234-123456789012",
                "name": "firstname",
                "label": "test",
                "attribute_type": "String",
                "type": "employee/attribute_definition",
                "system": "true"
            },
            {
                "id": "87654321-1234-1234-1234-123456789012",
                "name": "lastname",
                "label": "test",
                "attribute_type": "String",
                "type": "employee/attribute_definition",
                "system": "true"
            },
        ]

### POST Create a new employee attribute definition [POST]

Create a new employee attribute definition
By default account_id is equal Account.current.id

+ Attributes
  + name: lastname (string, required)
  + label: test label (string)
  + attribute_type: String (string, required)
  + system: True (boolean, required)

+ Request (application/json)

        {
            "name": "lastname",
            "system": "true",
            "label": "test",
            "attribute_type": "String"
        }

+ Response 201 (application/json)

        {

            "id": "87654321-1234-1234-1234-123456789012",
            "name": "lastname",
            "label": "test",
            "attribute_type": "String",
            "type": "employee/attribute_definition",
            "system": "true"
        }

## Employee Attribute Definition [/api/v1/employee_attribute_definitions/{employee_attribute_definition_id}]

+ Parameters
  + employee_attribute_definition_id: 12345678-1234-1234-123456789012 (required, string) - ID is in uuid format

### GET Employee Attribute Definition Details [GET]

+ Request (application/json)

+ Response 200 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "firstname",
            "label": "test",
            "attribute_type": "String",
            "type": "employee/attribute_definition",
            "system": "true"
        }

### PUT Update Employee Attribute Definition [PUT]

+ Attributes
  + id: 1 (string, required)
  + name: lastname (string, required)
  + label: test label (string)
  + attribute_type: String (string, required)
  + system: True (boolean, required)

+ Request (application/json)

        {
            "label": "test",
            "system": "true",
            "type": "String",
            "name": "firstname"
        }

+ Response 204 (application/json)

### DELETE destroy Employee Attribute Definiiton [DELETE]

+ Request (application/json)

+ Response 204






## Holiday Policies Collection [/api/v1/holiday_policies]

### GET List of all account's holiday policies [GET]
Get a list of all available for account holiday policies

+ Request (application/json)

+ Response 200 (application/json)
        [
            {
                "name": "test",
                "country": "pl",
                "region": null,
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "holiday_policy"
            },
            {
                "name": "test",
                "country": "ch",
                "region": "zh",
                "id": "87654321-1234-1234-1234-123456789012",
                "type": "holiday_policy"
            }
        ]

### POST Create a holiday policy [POST]

Create a new holiday_policy
By default account_id is equal Account.current.id

+ Attributes
  + name: test (string, required)
  + country: ch (string)
  + region: zh (string)
  + employees: [employees: {"id": "1"}] (array)
  + working_places: [working_places: {"id": "1"}] (array)
  + holidays: [holidays: {"id": "1"}] (array)

+ Request (application/json)

        {
             "name" : "test",
             "country": "ch",
             "region": "zh",
             "type": "holiday_policy",
             "employees" : [
                 {
                     "id": "12345678-1234-1234-1234-123456789012",
                     "type": "employee"
                 },
                 {
                     "id": "87654321-1234-1234-1234-123456789012",
                     "type": "employee"
                 }
              ],
              "working_places" : [
                  {
                      "id": "12345678-1234-1234-1234-123456789012"
                  }
              ],
              "holidays": [
                  {
                      "id": "12345678-1234-1234-1234-123456789012"
                  }
              ]
        }

+ Response 201 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "test"
            "country": "ch",
            "region": "zh",
            "type": "holiday_policy"
        }

## Holiday Policy [/api/v1/holiday_policies/{holiday_policy_id}]

+ Parameters
    + holiday_policy_id: 12345678-1234-1234-123456789012 (required, string) - ID of the Holiday Policy is an uuid

### GET Get Holiday Policy Details [GET]

+ Request (application/json)

+ Response 200 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "test",
            "country": "ch",
            "region": "zh",
            "type": "holiday_policy"
        }

### PUT Update Holiday Policy [PUT]

+ Attributes
  + id: 1 (string, required)
  + name: test (string, required)
  + country: ch (string)
  + region: zh (string)
  + employees: [employees: {"id": "1"}] (array)
  + working_places: [working_places: {"id": "1"}] (array)
  + holidays: [holidays: {"id": "1"}] (array)

+ Request (application/json)

        {
            "name": "Poland",
            "country" : "pl"
        }

+ Response 204 (application/json)

### DELETE

+ Request (application/json)

+ Response 204




## Holiday Collection [/api/v1/holiday_policies/{holiday_policy_id}/holidays]

+ Parameters
   + holiday_policy_id: 12345678-1234-1234-123456789012 (required, string) - ID is in uuid format

### GET List of all holiday_policy holidays [GET]

Get a list of holidays which belongs to particular holiday_policy

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
              "date": "01/01",
              "id": "87654321-1234-1234-1234-123456789012",
              "type": "holiday"
            },
            {
              "date": "01/01",
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "holiday"
            }
        ]

### POST Create a holiday [POST /api/v1/holidays]

Create a new holiday

+ Attributes
  + name: holiday (string, required)
  + date: 1 (string, required)
  + holiday_policy
    + id: 11 (string, required)

+ Request (application/json)

        {
            "name": "holiday",
            "date": "01.01.2013",
            "holiday_policy": {
              "id": "12345678-1234-1234-1234-123456789012"
            }
        }

+ Response 201 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "holiday",
            "type": "holiday"
        }

## Holiday [/api/v1/holidays/{holiday_id}]

+ Parameters
    + holiday_id: 12345678-1234-1234-123456789012 (required, string) - ID of the Holiday is an uuid

### GET Get Holiday Details [GET /api/v1/holidays/{holiday_id}]

+ Parameters
   + holiday_id: 12345678-1234-1234-123456789012 (required, string) - ID of the Holiday is an uuid

+ Request (application/json)

+ Response 200 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "holiday",
            "type": "holiday",
            "date": "01/01"
        }

### PUT Update Holiday [PUT]

+ Attributes
  + id: 1 (string, required)
  + name: holiday (string, required)
  + date: 1 (string, required)

+ Request (application/json)

        {
            "name": "holiday",
            "date" : "01.01.2015"
        }

+ Response 204 (application/json)

### DELETE holiday [DELETE]

+ Attributes
  + holiday_policy_id: 1 (string, required)

+ Request (application/json)

+ Response 204







## PresencePolicy Collection [/api/v1/presence_policies]

## GET List of all PresencePolicies [GET]

Get a list of presence_policies which belongs to current account

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
              "name": "test",
              "id": "87654321-1234-1234-1234-123456789012",
              "type": "presence_policy",
              "presence_days": [
                {
                  "name": "test",
                  "id": "87654321-1234-1234-1234-123456789012",
                  "hours": "7.50",
                  "type": "presence_day"
                },
                {
                  "name": "test2",
                  "id": "12345678-1234-1234-1234-123456789012",
                  "hours": "8.00",
                  "type": "presence_day"
                }
              ]
            },
            {
              "name": "test2",
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "presence_policy",
              "presence_days": [
                {
                  "name": "test",
                  "id": "87654321-1234-1234-1234-123456789012",
                  "hours": "7.50",
                  "type": "presence_day"
                },
                {
                  "name": "test2",
                  "id": "12345678-1234-1234-1234-123456789012",
                  "hours": "8.00",
                  "type": "presence_day"
                }
              ]
            }
        ]

### POST Create a PresencePolicy [POST]

Create a new Policy of Presence
By default account_id is equal Account.current.id

+ Attributes
  + name: test (string, required)
  + employees: [employees: {"id": "1"}] (array)
  + working_places: [working_places: {"id": "1"}] (array)
  + presence_days: [days: {"id": "1"}] (array)

+ Request (application/json)

        {
             "name" : "test",
             "type": "presence_policy",
             "employees" : [
                 {
                     "id": "12345678-1234-1234-1234-123456789012",
                     "type": "employee"
                 },
                 {
                     "id": "87654321-1234-1234-1234-123456789012",
                     "type": "employee"
                 }
              ],
              "working_places" : [
                  {
                      "id": "12345678-1234-1234-1234-123456789012"
                  }
              ],
              "presence_days": [
                  {
                      "id": "12345678-1234-1234-1234-123456789012"
                  }
              ]
        }

+ Response 201 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "test",
            "type": "presence_policy",
            "presence_days": [
              {
                "name": "test",
                "id": "87654321-1234-1234-1234-123456789012",
                "hours": "7.50"
                "type": "presence_day"
              },
              {
                "name": "test2",
                "id": "12345678-1234-1234-1234-123456789012",
                "hours": "8.00"
                "type": "presence_day"
              }
            ]
        }




## PresencePolicy [/api/v1/presence_policies/{presence_policy_id}]

+ Parameters
    + presence_policy_id: 12345678-1234-1234-123456789012 (required, string) - ID is an uuid

### GET Get PresencePolicy [GET]

+ Request (application/json)

+ Response 200 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "test",
            "type": "presence_policy",
            "presence_days": [
              {
                "name": "test",
                "id": "87654321-1234-1234-1234-123456789012",
                "hours": "7.50",
                "type": "presence_day"
              },
              {
                "name": "test2",
                "id": "12345678-1234-1234-1234-123456789012",
                "hours": "8.00",
                "type": "presence_day"
              }
            ]
        }

### PUT Update PresencePolicy [PUT]

+ Attributes
  + id: 1 (string, required)
  + name: presence name (string, required)
  + employees: [employees: {"id": "1"}] (array)
  + working_places: [working_places: {"id": "1"}] (array)
  + presence_days: [presence_days: {"id": "1"}] (array)

+ Request (application/json)

        {
            "type": "presence_policy",
            "name": "presence name"
        }

+ Response 204 (application/json)

### DELETE presence policy [DELETE]

+ Request (application/json)

+ Response 204








## PresenceDays Collection [/api/v1/presence_policies/{presence_policy_id}/presence_days]

+ Parameters
   + presence_policy_id: 12345678-1234-1234-123456789012 (required, string) - ID is in uuid format

## GET List of all PresenceDays [GET]

Get a list of presence days which belongs to account's presence policy

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
              "order": "1",
              "id": "87654321-1234-1234-1234-123456789012",
              "minutes": "750"
              "type": "presence_day"
            },
            {
              "order": "2",
              "id": "12345678-1234-1234-1234-123456789012",
              "minutes": "800"
              "type": "presence_day"
            }
        ]

### POST Create a PresenceDay [POST]

Create a new presence day

+ Attributes
  + order: 1 (number, required)
  + presence_policy: (required)
    + id: 11 (string, required)
  + hours: 8 (number, required)

+ Request (application/json)

        {
            "order" : "1",
            "type": "presence_day",
            "hours: "8.00",
            "presence_policy": {
              "id": "12345678-1234-1234-1234-123456789012"
            }
        }


+ Response 201 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "order": "1",
            "hours": "8.00",
            "type": "presence_day"
        }






## PresenceDay [/api/v1/presence_days/{presence_day_id}]

+ Parameters
    + presence_day_id: 12345678-1234-1234-123456789012 (required, string) - ID is an uuid

### GET PresenceDay Details [GET /api/v1/presence_days/{presence_day_id}]

+ Parameters
   + presence_day_id: 12345678-1234-1234-123456789012 (required, string) - ID of the Holiday is an uuid

+ Request (application/json)

+ Response 200 (application/json)

         {
            "id": "12345678-1234-1234-1234-123456789012",
            "order": "1",
            "hours": "8.00",
            "type": "presence_day"
        }

### PUT Update PresenceDay [PUT]

+ Attributes
  + id: 1 (string, required)
  + order: 1 (number, required)
  + hours: 8 (number, required)

+ Request (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "order": "1",
            "hours": "8.00",
            "type": "presence_day",
        }

+ Response 204 (application/json)


### DELETE PresenceDay [DELETE]

+ Attributes
  + presence_policy_id: 1 (string, required)

+ Request (application/json)

+ Response 204







## Time Entry


## Time Entry Collection [/api/v1/time_entries]

### GET Time Entries [GET /api/v1/presence_days/{presence_day_id}/time_entries]

Get list of time entries

+ Request (application/json)

        {
          "time_entry_id": "f6d72193-ba17-44be-835a-77b4b80c395b"
        }

+ Response 200 (application/json)

        [
          {
            "start_time": "12:00",
            "end_time": "14:00",
            "id": "1b1f9c6b-6740-4296-81cc-7fc316db3190",
            "type": "time_entry",
            "presence_day": {
              "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
              "type": "presence_day"
            }
          },
          {
            "start_time": "15:00",
            "end_time": "17:00",
            "id": "1b1f9c6b-6740-4296-81cc-7fc316db3000",
            "type": "time_entry",
            "presence_day": {
              "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
              "type": "presence_day"
            }
          }
        ]

### POST Time entry [POST]

Create new Time Entry

+ Attributes
  + type: time_entry(string)
  + end_time: test(string, required)
  + start_time: test(string, required)
  + presence_day (required)
    + id: 11 (string, required)

+ Request (application/json)

        {
          "type": "time_entry",
          "start_time": "12:00"
          "end_time": "02:00",
          "presence_day": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "presence_day"
          }
        }

+ Response 201 (application/json)

        {
          "type": "time_entry",
          "start_time": "12:00"
          "end_time": "02:00",
          "id": "92ebd78d-aaaa-464b-a93d-b0ba36fdbea0",
          "presence_day": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "presence_day"
          }
        }

## Time Entry [/api/v1/time_entries/{time_entry_id}]

### GET Time Entry [GET]

Show Time Entry

+ Request (application/json)

        {
          "time_entry_id": "1b6de77e-c9cf-453e-951d-6e6dd6cea1f7"
        }

+ Response 200 (application/json)

        {
          "type": "time_entry",
          "start_time": "12:00"
          "end_time": "14:00",
          "id": "1b6de77e-c9cf-453e-951d-6e6dd6cea1f7",
          "presence_day": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "presence_day"
          }
        }


### PUT Time Entry [PUT]

Update Time Entry.

+ Attributes
  + type: time_entry(string)
  + end_time: test(string, required)
  + id: 11(string, required)
  + start_time: test(string, required)
  + presence_day (required)
    + id: 11 (string, required)

+ Request (application/json)

        {
          "type": "time_entry",
          "start_time": "22:00"
          "end_time": "02:00",
          "id": "1b6de77e-c9cf-453e-951d-6e6dd6cea1f7",
          "presence_day": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "presence_day"
          }
        }

+ Response 204

### DELETE Delete Time Entry [DELETE]

Delete time entry (or two if related time entry was created)

+ Request (application/json)

+ Response 204









## Working Places Collection [/api/v1/working_places]

### GET List all user's working places [GET]

Get a list of all available for user working places

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "name": "test-working-place",
              "type": "working_place"
            },
            {
              "id": "87654321-1234-1234-1234-123456789012",
              "name": "test-test",
              "type": "working_place"
            }
        ]

### POST Create a working place [POST]

Create a new working place
By default account_id is equal Account.current.id

+ Attributes
  + name: Test (string, required)
  + type: working_place (string)
  + [time_off_policies: {"id": "1"}] (array)

+ Request (application/json)

        {
            "name": "Office",
            "type": "working_place",
            "time_off_policies": [
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "time_off_policy"
              },
              {
                "id": "12345678-1234-4444-1234-123456789012",
                "type": "time_off_policy"
              }
            ]
        }

+ Response 201 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "test-working-place",
            "type": "working_place",
            "time_off_policies": [
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "time_off_policy"
              },
              {
                "id": "12345678-1234-4444-1234-123456789012",
                "type": "time_off_policy"
              }
            ]
        }

## Working Place [/api/v1/working_places/{working_place_id}]

+ Parameters
    + working_place_id: 1ab (required, string) - ID of the Working Place is an uuid

### GET Get Working Place Details [GET]

+ Request (application/json)

+ Response 200 (application/json)

        {
            "id": "12345678-1234-1234-1234-123456789012",
            "name": "test-working-place",
            "type": "working_place",
            "time_off_policies": [
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "time_off_policy"
              },
              {
                "id": "12345678-1234-4444-1234-123456789012",
                "type": "time_off_policy"
              }
            ]
        }

### GET Get Working Place Details with holiday policy [GET /api/v1/working_places/{working_place_id}?embed=holiday_policy]

+ Response 200 (application/json)

        {
            "id": "12345678-5678-1234-1234-123456789012",
            "name": "test-working-place",
            "type": "working_place",
            "holiday_policy": {
              "id": "12345678-1234-1234-1234-123456789012",
              "name": "test",
              "country": "pl",
              "region": "ds",
              "type": "holiday_policy"
            }
        }

### GET Get Working Place Details with holiday policy and its holidays [GET /api/v1/working_places/{working_place_id}?embed=holiday_policy.holidays]

+ Response 200 (application/json)

        {
            "id": "12345678-5678-1234-1234-123456789012",
            "name": "test-working-place",
            "type": "working_place",
            "holiday_policy": {
              "id": "12345678-1234-1234-1234-123456789012",
              "name": "test",
              "country": "pl",
              "region": "ds",
              "type": "holiday_policy"
              "holidays": [
                {
                  "id": "87654321-1234-1234-1234-123456789012",
                  "holiday_policy_id": "12345678-1234-1234-1234-123456789012",
                  "name": "test",
                  "date": "01.01.2015",
                  "type": "holiday"
                }
              }
            ]
        }

### PUT Update Working Place name [PUT]

+ Attributes
    + name: New name (required, string) - New name for working place
    + type: working_place (string)

+ Request (application/json)

        {
            "name": 'Smaple name',
            "type": "working_place",
            "time_off_policies": [
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "time_off_policy"
              },
              {
                "id": "12345678-1234-4444-1234-123456789012",
                "type": "time_off_policy"
              }
            ]
        }

+ Response 204

### DELETE Delete working place [DELETE]

+ Request (application/json)

+ Response 204




## Employees [/api/v1/employees]

### GET List all employees with attributes [GET]

Get a list of all employees

+ Request (application/json)

+ Response 200 (application/json)

        [
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee",
              "employee_attributes": [
                {
                  "id": "12345678-1234-1234-1234-123456789012",
                  "type": "employee_attribute",
                  "value": "ABC",
                  "attribute_name": "lastname"
                },
                {
                  "id": "12345678-1234-1234-1234-123456789013",
                  "type": "employee_attribute",
                  "value": "Asd",
                  "attribute_name": "firstname"
                }
              ]
            },
            {
              "id": "87654321-1234-1234-1234-123456789012",
              "type": "employee",
              "employee_attributes": [
                {
                  "id": "12345678-1234-1234-1234-123456789012",
                  "type": "employee_attribute",
                  "value": "ABC",
                  "attribute_name": "firstname"
                }
              ]
            }
        ]

### GET Employee details [GET /api/v1/employees/{employee_id}]

+ Parameters
  + employee_id: 12 (required, string) - ID is in uuid format

+ Request (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789012",
          "type": "employee",
          "employee_attributes": [
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "ABC",
              "attribute_name": "firstname"
            },
            {
              "id": "12345678-1234-1234-1234-123456789013",
              "type": "employee_attribute",
              "value": "Asd",
              "attribute_name": "lastname"
            }
          ],
          "time_off_policies": [
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "time_off_policy"
              },
              {
                "id": "12345678-1234-4444-1234-123456789012",
                "type": "time_off_policy"
              }
          ]
        }

### PUT Employee [PUT /api/v1/employees/{employee_id}]

+ Parameters
  + employee_id: 12 (required, string) - ID is in uuid format
  + holiday_policy
    + id: 12 (required, string)
  + presence_policy
    + id: 13 (required, string)
  + time_off_policies: {"id": "1"} (array)

+ Request (application/json)

        {
            "holiday_policy': {
              "id": "12345",
              "type": "holiday_policy"
            },
            "presence_policy": {
              "id": "12345",
              "type": "holiday_policy"
            },
            "time_off_policies": [
              {
                "id": "123",
                "type": "time_off_policy"
              },
              {
                "id": "654",
                "type": "time_off_policy"
              }
            ]
        }

+ Response 204




## Employee events [/api/v1/employee_events]

### GET Employee events [GET /api/v1/employee_events?employee_id={employee_id}]

+ Request (application/json)

        {
          "employee_id": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        [
          {
            "id": "12345678-1234-1234-1234-123456789013",
            "type": "employee_event",
            "effective_at": "2015.02.02",
            "comment": "Random",
            "event_type": "hired",
            "employee": {
              "id": "123",
              "type": "employee",
            },
            "employee_attributes": [
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "employee_attribute",
                "value": "ABC",
                "attribute_name": "lastname"
              },
              {
                "id": "12345678-1234-1234-1234-123456789012",
                "type": "employee_attribute",
                "value": "Dsa",
                "attribute_name": "firstname"
              }
            ]
          }
        ]

### GET Employee event [GET /api/v1/employee_events/{employee_event_id}]

+ Request (application/json)

        {
          "employee_event_id": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "employee_event",
          "effective_at": "2015.02.02",
          "comment": "Random",
          "event_type": "hired",
          "employee": {
            "id": "123",
            "type": "employee",
          },
          "employee_attributes": [
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "ABC",
              "attribute_name": "lastname"
            },
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "Dsa",
              "attribute_name": "firstname"
            }
          ]
        }


### POST Employee event [POST /api/v1/employee_events]

+ Request (application/json)

        {
          "type": "employee_event",
          "effective_at": "2015.02.02",
          "comment": "Random",
          "event_type": "hired",
          "employee":
          {
            "type": "employee",
          },
          "employee_attributes": [
            {
              "type": "employee_attribute",
              "value": "ABC",
              "attribute_name": "lastname"
            },
            {
              "type": "employee_attribute",
              "value": "Dsa",
              "attribute_name": "firstname"
            }
          ]
        }

+ Response 201 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "employee_event",
          "effective_at": "2015.02.02",
          "comment": "Random",
          "event_type": "hired",
          "employee": {
            "id": "123",
            "type": "employee",
          },
          "employee_attributes": [
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "ABC",
              "attribute_name": "lastname"
            },
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "Dsa",
              "attribute_name": "firstname"
            }
          ]
        }

### PUT Employee event [PUT /api/v1/employee_events/{employee_event_id}]

+ Request (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "employee_event",
          "effective_at": "2015.02.02",
          "comment": "Random",
          "event_type": "hired",
          "employee": {
            "id": "123",
            "type": "employee",
          },
          "employee_attributes": [
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "ABC",
              "attribute_name": "lastname"
            },
            {
              "id": "12345678-1234-1234-1234-123456789012",
              "type": "employee_attribute",
              "value": "Dsa",
              "attribute_name": "firstname"
            }
          ]
        }

+ Response 204










## Time Off Category


## Time Off Categories Collection [/api/v1/time_off_categories]

### GET Time Off Categories [GET]

Get a list of time off categories

+ Request (application/json)

+ Response 200 (application/json)

        [
          {
            "name": "example name",
            "system": "false",
            "id": "12345678-1234-1234-1234-123456789012",
            "type": "time_off_category"
          },
          {
            "name": "test name",
            "system": "true",
            "id": "12345678-1234-4444-1234-123456789012",
            "type": "time_off_category"
          }
        ]

### POST Time off Category [POST]

Create new time off category, every category created by user, by default has system: false
Default time off category for every account is sickness.

+ Attributes
  + name: test(string, required)
  + type: time_off_category(string)

+ Request (application/json)

        {
          "name": "test",
          "type": "time_off_category"
        }

+ Response 201 (application/json)

        {
          "name": "test",
          "system": false,
          "id": "5921da5e-759e-4902-bd75-bca42e5457f6",
          "type": "time_off_category"
        }


## Time Off Category [/api/v1/time_off_categories/{time_off_category_id}]

### GET Time off Category [GET]

Show Time Off Category

+ Request (application/json)

        {
          "time_off_category_id": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789012",
          "name": "test",
          "system": false,
          "type": "time_off_category"
        }


### PUT Time Off Category [PUT]

Update Time Off Category

+ Attributes
  + id: 11 (string, required)
  + name: test (string, required)
  + type: time_off_category(string)

+ Request (application/json)

        {
          "name": "test",
          "id": "11",
          "type": "time_off_category"
        }

+ Response 204

### DELETE Delete Time Off Category [DELETE]

Delete time off category

+ Request (application/json)

+ Response 204








## Time Off


## Time Off Collection [/api/v1/time_offs]

### GET Time Offs [GET /api/v1/time_offs/{time_off_category_id}/time_offs]

Get a list of time offs

+ Request (application/json)

        {
          "time_off_category_id": "f6d72193-ba17-44be-835a-77b4b80c395b"
        }

+ Response 200 (application/json)

        [
          {
            "start_time": "2015-12-14T09:43:34.744Z",
            "end_time": "2015-12-21T09:43:34.744Z",
            "id": "1b1f9c6b-6740-4296-81cc-7fc316db3190",
            "type": "time_off",
            "employee": {
              "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
              "type": "employee"
            },
            "time_off_category": {
              "id": "f6d72193-ba17-44be-835a-77b4b80c395b",
              "type": "time_off_category"
            }
          },
          {
            "start_time": "2015-11-14T12:00:18.000Z",
            "end_time": "2015-12-14T12:00:18.000Z",
            "id": "f3b3989c-dee0-4ed9-8e49-8e3b0d6db587",
            "type": "time_off",
            "employee": {
              "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
              "type": "employee"
            },
            "time_off_category": {
              "id": "f6d72193-ba17-44be-835a-77b4b80c395b",
              "type": "time_off_category"
            }
          }
        ]

### POST Time off [POST]

Create new time off

+ Attributes
  + type: time_off(string)
  + end_time: test(string, required)
  + start_time: test(string, required)
  + time_off_category (required)
    + id: 11 (string, required)
  + employee (required)
    + id: 22 (string, required)

+ Request (application/json)

        {
          "type": "time_off",
          "employee": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "employee"
          },
          "time_off_category": {
            "id": "f6d72193-ba17-44be-835a-77b4b80c395b",
            "type": "time_off_category"
          },
          "end_time": "12.12.2015",
          "start_time": "11.12.2015"
        }

+ Response 201 (application/json)

        {
          "start_time": "2015-12-11T00:00:00.000Z",
          "end_time": "2015-12-12T00:00:00.000Z",
          "id": "1b6de77e-c9cf-453e-951d-6e6dd6cea1f7",
          "type": "time_off",
          "employee": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "employee"
          },
          "time_off_category": {
            "id": "f6d72193-ba17-44be-835a-77b4b80c395b",
            "type": "time_off_category"
          }
        }


## Time Off [/api/v1/time_offs/{time_off_id}]

### GET Time off [GET]

Show Time Off

+ Request (application/json)

        {
          "time_off_id": "1b6de77e-c9cf-453e-951d-6e6dd6cea1f7"
        }

+ Response 200 (application/json)

        {
          "start_time": "2015-12-11T00:00:00.000Z",
          "end_time": "2015-12-12T00:00:00.000Z",
          "id": "1b6de77e-c9cf-453e-951d-6e6dd6cea1f7",
          "type": "time_off",
          "employee": {
            "id": "92ebd78d-15f1-464b-a93d-b0ba36fdbea0",
            "type": "employee"
          },
          "time_off_category": {
            "id": "f6d72193-ba17-44be-835a-77b4b80c395b",
            "type": "time_off_category"
          }
        }


### PUT Time Off [PUT]

Update Time Off

+ Attributes
  + type: time_off(string)
  + end_time: test(string, required)
  + start_time: test(string, required)

+ Request (application/json)

        {
          "type": "time_off",
          "end_time": "12.12.2015",
          "start_time": "11.12.2015"
        }

+ Response 204

### DELETE Delete Time Off [DELETE]

Delete time off

+ Request (application/json)

+ Response 204











## Employee Balances Collection [/api/v1/employee_balances]

### GET Employee balances without time_off_category_id param [GET /api/v1/employees/:employee_id/employee_balances]

Get a list of last balances in every category

+ Request (application/json)

        {
          "employee_id": "12345678-1234-1234-1234-123456789012",
        }

+ Response 200 (application/json)

        [
          {
            "id": "1234",
            "type": "employee_balance",
            "balance": "12345",
            "amount": "-100",
            "time_off_category": {
                "type": "time_off_category",
                "id": "11"
            },
            "id": "14",
            "type": "employee_balance",
            "balance": "12345",
            "amount": "200",
            "time_off_category": {
                "type": "time_off_category",
                "id": "22"
            }
        ]

### Get Employee balances with time_off_category_id param [GET /api/v1/employees/:employee_id/employee_balances?time_off_category_id={time_off_category_id}]

Get a history of employee balances in category

+ Request (application/json)

        {
          "employee_id": "12345678-1234-1234-1234-123456789012",
          "time_off_category_id": "12345678-4321-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        [
          {
            "id": "12345678-1234-1234-1234-123456789013",
            "type": "employee_balance",
            "balance": "2880",
            "amount": "1440"
          },
          {
            "id": "87654321-1234-1234-1234-123456789013",
            "type": "employee_balance",
            "balance": "1440",
            "amount": "1440"
          }
        ]

### POST Employee balance [POST /api/v1/employee_balances]

Create new employee balance, balance field is actual employee balance, amount is in minutes.

+ Attributes
  + type: employee_balance (string)
  + amount: 1440 (string)
  + employee (required)
    + type: employee (string)
    + id: 111 (string, required) - employee id
  + time_off_category (required)
    + type: time_off_category (string)
    + id: 222 (string, required) - time off category id

+ Request (application/json)


        {
          "type": "employee_balance",
          "amount": "1440",
          "employee": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "time_off_category": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          }
        }

+ Response 201 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "employee_balance",
          "balance": "2880",
          "amount": "1440",
          "employee": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "time_off_category": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          }
        }


## Employee Balance [/api/v1/employee_balances/{employee_balance_id}]

### GET Employee balance [GET]

Show employee balance

+ Request (application/json)

        {
          "employee_balance_id": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "employee_balance",
          "balance": "2880",
          "amount": "1440",
          "employee": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "time_off_category": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          },
           "time_off": {
            "type": "time_off",
            "id": "12345678-1234-4444-1234-123456789012"
          },
          "time_off_policy": {
            "type": "time_off_policy",
            "id": "12345678-1234-0000-1234-123456789012"
          }
        }


### PUT Employee balance [PUT]

Update employee Balance


+ Attributes
  + id: 11 (string, required)
  + type: employee_balance (string)
  + amount: 1440 (string)
  + employee (required)
    + type: employee (string)
    + id: 111 (string, required) - employee id
  + time_off_category (required)
    + type: time_off_category (string)
    + id: 222 (string, required) - time off category id

+ Request (application/json)

        {
          "type": "employee_balance",
          "amount": "1460",
          "employee": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "time_off_category": {
            "type": "employee",
            "id": "12345678-1234-1234-1234-123456789012"
          }
        }

+ Response 204

### DELETE Delete employee balance [DELETE]

Delete employee balance

+ Request (application/json)

+ Response 204






## Time Off Policies Collection [/api/v1/time_off_policies]

### Get time off policies [GET]

Get a list of time off policies

+ Request (application/json)

+ Response 200 (application/json)

        [
          {
            "id": "12345678-1234-1234-1234-123456789013",
            "type": "time_off_policy",
            "start_day": "1",
            "end_day": "1",
            "start_month": "1",
            "end_month": "4"
            "years_to_effect": "1",
            "years_passed": "0",
            "amount": "28800",
            "policy_type": "balancer",
            "time_off_category": {
              "type": "time_off_category",
              "id": "12345678-1234-1234-1234-123456789012"
            }
          },
          {
            "id": "87654321-1234-1234-1234-123456789013",
            "type": "time_off_policy",
            "start_day": "1",
            "end_day": "1",
            "start_month": "1",
            "end_month": "10",
            "years_to_effect": 0,
            "years_passed": "0",
            "amount": "0",
            "policy_type": "counter",
            "time_off_category": {
              "type": "time_off_category",
              "id": "12345678-1234-1234-1234-123456789012"
            }
          }
        ]

### GET time off policies by category [GET /api/v1/time_off_categories/:time_off_category_id/time_off_policies]

Get a list of time off policies in given category

+ Request (application/json)

        {
          "time_off_category": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        [
          {
            "id": "12345678-1234-1234-1234-123456789013",
            "type": "time_off_policy",
            "start_day": "1",
            "end_day": "1",
            "start_month": "1",
            "end_month": "4"
            "years_to_effect": "1",
            "years_passed": "0",
            "amount": "28800",
            "policy_type": "balancer",
            "time_off_category": {
              "type": "time_off_category",
              "id": "12345678-1234-1234-1234-123456789012"
            }
          },
          {
            "id": "87654321-1234-1234-1234-123456789013",
            "type": "time_off_policy",
            "start_day": "1",
            "end_day": "1",
            "start_month": "1",
            "end_month": "10",
            "years_to_effect": 0,
            "years_passed": "0",
            "amount": "",
            "policy_type": "counter",
            "time_off_category": {
              "type": "time_off_category",
              "id": "12345678-1234-1234-1234-123456789012"
            }
          }
        ]

### POST Time off Policy [POST /api/v1/time_off_policies]

Create new time off policy. Policy may have two types: counter of balance, if type counter amount should not be send.

+ Attributes
  + name: Example (string)
  + type: time_off_policy (string)
  + amount: 1440 (string)
  + policy_type: balancer (string, required)
  + start_day: 1(number, required)
  + end_day: 1(number)
  + start_month: 1(number, required)
  + end_month: 10(number)
  + years_to_effect: 1 (number)
  + time_off_category (required)
    + type: time_off_category (string)
    + id: 11 (string, required)
  + [employees: {"id": "1"}] (array)
  + [working_places: {"id": "1"}] (array)

+ Request (application/json)

        {
          "name": "Example",
          "type": "time_off_policy",
          "start_day": "1",
          "end_day": "1",
          "start_month": "1",
          "end_month": "10",
          "amount": "1440",
          "years_to_effect": "1",
          "policy_type": "balancer"
          "time_off_category": {
            "type": "time_off_category",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "employees" : [
             {
                 "id": "12345678-1234-1234-1234-123456789012",
                 "type": "employee"
             },
             {
                 "id": "87654321-1234-1234-1234-123456789012",
                 "type": "employee"
             }
          ],
          "working_places" : [
              {
                  "id": "12345678-1234-1234-1234-123456789012"
              }
          ]
        }


+ Response 201 (application/json)

         {
          "id": "12345678-1234-1234-1234-123456789013",
          "name": "Example",
          "type": "time_off_policy",
          "start_day": "1",
          "end_day": "1",
          "start_month": "1",
          "end_month": "10",
          "amount": "1440",
          "years_to_effect": "1",
          "years_passed": "0",
          "policy_type": "balancer",
          "time_off_category": {
            "type": "time_off_category",
            "id": "12345678-1234-1234-1234-123456789012"
          }
        }


## Time Off Policy [/api/v1/time_off_policies/{time_off_policy_id}]

### GET Time Off Policy [GET]

Show time off policy

+ Request (application/json)

        {
          "time_off_policy_id": "12345678-1234-1234-1234-123456789012"
        }

+ Response 200 (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "name": "Example",
          "type": "time_off_policy",
          "start_day": "1",
          "end_day": "1",
          "start_month": "1",
          "end_month": "10",
          "amount": "1440",
          "policy_type": "balancer",
          "years_to_effect": "1",
          "years_passed": "0",
          "time_off_category": {
            "type": "time_off_category",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "employees" : [
             {
                 "id": "12345678-1234-1234-1234-123456789012",
                 "type": "employee"
             },
             {
                 "id": "87654321-1234-1234-1234-123456789012",
                 "type": "employee"
             }
          ],
          "working_places" : [
              {
                  "id": "12345678-1234-1234-1234-123456789012"
              }
          ]
        }


### PUT Time off Policy [PUT]

Update time off policy

+ Attributes
  + name: Example (string)
  + type: time_off_policy (string)
  + amount: 1440 (string)
  + policy_type: balancer (string, required)
  + start_day: 1(number, required)
  + end_day: 1(number)
  + start_month: 1(number, required)
  + end_month: 10(number)
  + years_to_effect: 1(number, required)
  + [employees: {"id": "1"}] (array)
  + [working_places: {"id": "1"}] (array)

+ Request (application/json)

        {
          "id": "12345678-1234-1234-1234-123456789013",
          "name": "Example",
          "type": "time_off_policy",
          "start_day": "1",
          "end_day": "1",
          "start_month": "1",
          "end_month": "10",
          "years_to_effect": "1",
          "years_passed": "0",
          "amount": "1440",
          "policy_type": "balancer",
          "time_off_category": {
            "type": "time_off_category",
            "id": "12345678-1234-1234-1234-123456789012"
          },
          "employees" : [
             {
                 "id": "12345678-1234-1234-1234-123456789012",
                 "type": "employee"
             },
             {
                 "id": "87654321-1234-1234-1234-123456789012",
                 "type": "employee"
             }
          ],
          "working_places" : [
              {
                  "id": "12345678-1234-1234-1234-123456789012"
              }
          ]
        }


+ Response 204

### DELETE Delete Time Off Policy [DELETE]

+ Request (application/json)

+ Response 204


## Users Collection [/api/v1/users]

### Get Users [GET]

Get a list of users

+ Request (application/json)

+ Response 200 (application/json)

        [
          {
            "email": "yalty@company.com",
            "account_manager": true,
            "is_employee": false,
            "id": "12345678-1234-1234-1234-123456789013",
            "type": "account_user",
            "employee": null
          },
          {
            "email": "test@example.com",
            "account_manager": false,
            "is_employee": true,
            "id": "12345678-1234-1234-1234-123456789013",
            "type": "account_user",
            "employee":
              {
                "id": "12345678-1234-1234-1234-123456789013",
                "type": "employee"
              }
          }
        ]

### POST Create a new account user [POST /api/v1/users]

Create a new User
By default account_id is equal Account.current.id

+ Attributes
  + type: "account_user" (string)
  + password: "12345678" (string)
  + email: "test@example.com" (string)
  + account_manager: false (boolean)
  + employee:
    + id: "11" (string, required)
    + type: "employee" (string)

+ Request (application/json)

        {
            "email": "test@example.com",
            "password": "12345678",
            "account_manager": false,
            "type": "account_user",
            "employee":
              {
                "id": "12345678-1234-1234-1234-123456789013",
                "type": "employee"
              }
        }

+ Response 201 (application/json)

        {
          "email": "test@example.com",
          "account_manager": false,
          "is_employee": true,
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "account_user",
          "employee":
            {
              "id": "12345678-1234-1234-1234-123456789013",
              "type": "employee"
            }
        }


## User [/api/v1/users/{user_id}]

### Get users [GET]

Show user

+ Request (application/json)

+ Response 200 (application/json)

        {
          "email": "test@example.com",
          "account_manager": false,
          "is_employee": true,
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "account_user",
          "employee":
            {
              "id": "12345678-1234-1234-1234-123456789013",
              "type": "employee"
            }
        }


### PUT Time off Policy [PUT]

Update user

+ Attributes
  + type: "account_user" (string)
  + email: "test@example.com" (string)
  + account_manager: true (boolean)
  + employee:
    + id: "11" (string, required)
    + type: "employee" (string)

+ Request (application/json)

        {
          "email": "test@example.com",
          "account_manager": false,
          "id": "12345678-1234-1234-1234-123456789013",
          "type": "account_user",
          "employee":
            {
              "id": "12345678-1234-1234-1234-123456789013",
              "type": "employee"
            }
        }


+ Response 204 (application/json)
