StripeSubscription = Struct.new(:id, :current_period_end, :quantity)
StripeCustomer = Struct.new(:id, :description, :save)
StripeInvoice = Struct.new(:id, :amount_due, :date, :lines)
StripePlan = Struct.new(:id, :amount, :currency, :interval, :name, :active)
StripeSubscriptionItem = Struct.new(:id, :plan, :delete)
