default: &default
  adapter: postgresql
  username: rails
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: yalty_development

test:
  <<: *default
  database: yalty_test

staging:
  <<: *default
  database: yalty_staging

production:
  <<: *default
  database: yalty_production
