default: &default
  adapter: postgresql
  username: rails
  encoding: unicode
  pool: <%= ENV["DB_POOL"] || ENV['MAX_THREADS'] || 5 %>

development:
  <<: *default
  database: yalty_development

test:
  <<: *default
  database: yalty_test<%= ENV['TEST_ENV_NUMBER']%>

staging:
  <<: *default
  database: yalty_staging

review:
  <<: *default
  database: yalty_review

production:
  <<: *default
  database: yalty_production
