every_midnight:
  cron: "0 0 * * *"
  class: "AddPolicyAdditionsJob"
  args:
  queue: policies_and_balances
  description: "Check policies start dates and create addition balances if policy start date is today"

every_midnight:
  cron: "0 0 * * *"
  class: "AddRegisteredWorkingTimes"
  args:
  queue: registered_working_times
  description: "Adds the user registered working time from previous day"

every_one_am:
  cron: "0 1 * * *"
  class: "AddBalanceRemovalsJob"
  args:
  queue: policies_and_balances
  description: "Check employee balances validity dates and create removals if validity date is today"
