every_midnight_policy_add:
  cron: "0 0 * * *"
  class: "CreateAdditionsAndRemovals"
  args:
  queue: policies_and_balances
  description: "Create balances in advance for active EmployeeTimeOffPolicy up to next period"

every_midnight_add_working_time:
  cron: "0 0 * * *"
  class: "AddRegisteredWorkingTimes"
  args:
  queue: registered_working_times
  description: "Adds the user registered working time from previous day"
