:concurrency: 1
:pidfile: tmp/pids/sidekiq.pid
:logfile: log/sidekiq.log
:queues:
  - mailers
  - policies_and_balances
  - update_balance
  - intercom
  - registered_working_times
  - employee_files
  - default
