:concurrency: <%= ENV['SIDEKIQ_CONCURRENCY'] || 3 %>
:workers: <%= ENV['SIDEKIQ_WORKERS'] || 1 %>
:pidfile: tmp/pids/sidekiq.%i.pid
:logfile: log/sidekiq.log
:queues:
  - billing
  - mailers
  - policies_and_balances
  - update_balance
  - intercom
  - registered_working_times
  - generic_files
  - default
:limits:
  update_balance: 1
