every_midnight_policy_add:
  cron: "0 0 * * *"
  class: "CreateAdditionsAndRemovals"
  args:
  queue: policies_and_balances
  description: "Create balances in advance for active EmployeeTimeOffPolicy up to next period"

every_midnight_add_working_time:
  cron: "0 0 * * *"
  class: "AddRegisteredWorkingTimes"
  args:
  queue: registered_working_times
  description: "Adds the user registered working time from previous day"

every_midnight_remove_orphan_files:
  cron: "0 0 * * *"
  class: "RemoveOrphanGenericFiles"
  args:
  queue: generic_files
  description: "Remove files not assigned to employees"

every_day_check_if_update_quantity:
  cron: "5 0 * * *"
  class: "::Payments::UpdateSubscriptionQuantity"
  args:
  queue: billing
  description: "Check if any new or leaving employess tomorrow and update quantity of plans"

every_hour_employees_journal_export:
  cron: "0 * * * *"
  class: "::Export::ScheduleEmployeesJournalExport"
  args:
  queue: export
  description: "Schedule export of employees journal for accounts with yalty special access"

every_hour_employees_payslips_import:
  cron: "0 * * * *"
  class: "::Import::SchedulePayslipsImport"
  args:
  queue: import
  description: "Schedule import of employees payslips"
