:concurrency: 1
:pidfile: <%= File.expand_path('./tmp/pids/sidekiq.pid', __dir__)  %>
:queues:
  - mailers
  - intercom
  - policies_and_balances
  - update_balance
  - registered_working_times
  - default
