#!/usr/bin/env ruby
require 'travis/pro'

#
# Configure
#

if ENV['GITHUB_ACCESS_TOKEN'].nil?
  puts 'GITHUB_ACCESS_TOKEN is not set'
  exit 1
end

Travis::Pro.github_auth(ENV['GITHUB_ACCESS_TOKEN'])

#
# Build docker image
#

def build_docker_image(branch, docker_tag)
  docker_repository = ENV['TRAVIS_REPO_SLUG'].gsub(%r{^yalty/yalty-}, 'yalty/')

  `git reset --hard #{branch} && git clean -d -x -f -f`
  `docker login -u="#{ENV['DOCKER_USERNAME']}" -p="#{ENV['DOCKER_PASSWORD']}"`
  `./bin/build #{docker_repository}:#{docker_tag}`
  `docker push #{docker_repository}:#{docker_tag}`
end

if ENV['TRAVIS_PULL_REQUEST'] != 'false' && ENV['TRAVIS_BRANCH'] == 'master'
  if ENV['TRAVIS_PULL_REQUEST_BRANCH'] =~ %r{^[^/]+/(ywa-[[:digit:]]+)}i
    docker_tag = Regexp.last_match(1).downcase
    build_docker_image('HEAD', docker_tag)
  elsif ENV['TRAVIS_PULL_REQUEST_BRANCH'] =~ %r{^releases?/(.+)}
    docker_tag = "#{Regexp.last_match(1)}-rc-#{ENV['TRAVIS_COMMIT']}"
    build_docker_image(ENV['TRAVIS_PULL_REQUEST_BRANCH'], docker_tag)
  end
elsif ENV['TRAVIS_BRANCH'] == 'master'
  build_docker_image('master', 'lastest')
end

#
# Restart build for same branch on e2e-testing repository
#

if ENV['TRAVIS_PULL_REQUEST'] == 'false'
  begin
    travis = Travis::Pro::Repository.find('yalty/yalty-e2e-testing')
    branch = ENV['TRAVIS_BRANCH']

    build = travis.branch(branch)
    if build.restartable?
      puts "Build ##{build.number} on yalty/yalty-e2e-testing for branch #{branch} restarted"
      build.restart
    end
  rescue Travis::Client::NotFound
    puts "Build on yalty/yalty-e2e-testing for branch #{branch} not found"
  end
end
