#!/bin/bash
(
  test "$TRAVIS_PULL_REQUEST" != "false" &&
  git fetch origin \
    $TRAVIS_PULL_REQUEST_BRANCH:refs/remotes/origin/$TRAVIS_PULL_REQUEST_BRANCH \
    $TRAVIS_BRANCH:refs/remotes/origin/$TRAVIS_BRANCH &&
  test $(git rev-list --left-only --count origin/$TRAVIS_BRANCH...origin/$TRAVIS_PULL_REQUEST_BRANCH) = 0
) || (
  bundle exec rake parallel:spec
)
